import { useCallback, useEffect, useState } from 'react';
import { Card,CardContent,CardHeader,CardTitle } from '@/components/ui/card'; import { Button } from '@/components/ui/button'; import { Badge } from '@/components/ui/badge'; import { Input } from '@/components/ui/input'; import { CalendarDays,Phone,PhoneOff,RefreshCw,CheckCircle,Search } from 'lucide-react'; import { supabase } from '@/integrations/supabase/client'; import { useToast } from '@/hooks/use-toast';
type Row={id:string;patient_name:string;patient_phone:string|null;vaccine_name:string|null;vaccine_type:string;appointment_date:string;appointment_time:string|null;status:string;reminder_channel:string;reminder_status:string};
const localDate=(offset=0)=>{const d=new Date();d.setDate(d.getDate()+offset);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
export default function AppointmentDayChecker(){const [date,setDate]=useState(localDate());const [rows,setRows]=useState<Row[]>([]);const [loading,setLoading]=useState(false);const {toast}=useToast();
 const load=useCallback(async()=>{setLoading(true);const {data,error}=await supabase.from('appointments').select('id,patient_name,patient_phone,vaccine_name,vaccine_type,appointment_date,appointment_time,status,reminder_channel,reminder_status').eq('appointment_date',date).in('status',['scheduled','pending']).order('appointment_time');setLoading(false);if(error){toast({title:'ค้นหานัดไม่สำเร็จ',description:error.message,variant:'destructive'});return;}setRows((data||[]) as unknown as Row[]);},[date,toast]); useEffect(()=>{void load()},[load]);
 const mark=async(r:Row,status:string)=>{const {data:{user}}=await supabase.auth.getUser();const {error}=await supabase.from('appointments').update({reminder_status:status,reminder_contacted_at:new Date().toISOString(),reminder_contacted_by:user?.email||user?.id||'staff'} as never).eq('id',r.id);if(error)toast({title:'บันทึกไม่สำเร็จ',description:error.message,variant:'destructive'});else{toast({title:'บันทึกการโทรแล้ว',description:r.patient_name});void load();}};
 const isTomorrow=date===localDate(1);return <Card><CardHeader><CardTitle className="flex items-center gap-2"><CalendarDays className="h-5 w-5"/>เช็คนัดตามวัน</CardTitle></CardHeader><CardContent className="space-y-4"><div className="flex flex-col md:flex-row gap-2 md:items-end"><div><label className="text-sm font-medium">เลือกวันที่นัด</label><Input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div><Button onClick={load} disabled={loading}><Search className="h-4 w-4 mr-1"/>แสดงรายชื่อ</Button><Button variant="outline" onClick={()=>{setDate(localDate())}}>วันนี้</Button><Button variant="outline" onClick={()=>{setDate(localDate(1))}}>พรุ่งนี้ / ต้องโทรแจ้ง</Button><Badge variant="secondary" className="h-8 px-3">{rows.length} คน</Badge></div>
 {isTomorrow&&<div className="rounded-md bg-amber-50 border border-amber-200 p-3 text-sm">รายการวันที่พรุ่งนี้คือกลุ่มที่เจ้าหน้าที่ควรโทรแจ้งล่วงหน้า 1 วัน สามารถบันทึกสถานะการโทรได้จากแต่ละรายชื่อ</div>}
 <div className="space-y-3">{rows.map(r=><div key={r.id} className="border rounded-lg p-4"><div className="flex flex-col lg:flex-row lg:items-center justify-between gap-3"><div><div className="font-semibold text-lg">{r.patient_name}</div><div className="text-sm text-muted-foreground">{r.appointment_time?.slice(0,5)||'ไม่ระบุเวลา'} • {r.vaccine_name||r.vaccine_type} • {r.patient_phone||'ไม่มีเบอร์โทร'}</div></div><div className="flex flex-wrap items-center gap-2"><Badge variant="outline">{r.status}</Badge><Badge>{r.reminder_status||'pending'}</Badge>{isTomorrow&&['phone','both'].includes(r.reminder_channel||'phone')&&<><Button size="sm" onClick={()=>mark(r,r.reminder_channel==='both'&&r.reminder_status==='line_sent'?'both_done':'phone_done')}><Phone className="h-4 w-4 mr-1"/>โทรแจ้งแล้ว</Button><Button size="sm" variant="outline" onClick={()=>mark(r,'unreachable')}><PhoneOff className="h-4 w-4 mr-1"/>ติดต่อไม่ได้</Button></>}</div></div></div>)}</div>
 {!rows.length&&!loading&&<div className="py-10 text-center text-muted-foreground"><CheckCircle className="h-10 w-10 mx-auto mb-2"/>ไม่มีรายชื่อนัดในวันที่เลือก</div>} {loading&&<div className="text-center py-6 text-muted-foreground"><RefreshCw className="h-5 w-5 animate-spin inline mr-2"/>กำลังโหลด...</div>}</CardContent></Card>}
